# Generated by Django 6.0.2 on 2026-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('staff', 'Staff Only'), ('student', 'Students Only'), ('private', 'Private'), ('shared', 'Shared Users Only')], default='private', max_length=20),
        ),
    ]
