# Generated by Django 6.0.2 on 2026-05-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
